http {

	# By default, limit is 1M
	# Upload < 1MB → OK
	# Upload > 1MB → 413 Request Entity Too Large
	client_max_body_size 50; (O = Octet (default unit), K = kilo-octet, M = mega-octet, G = giga-octet)

	server {

		# Ports from 0 to 1023 requires root privilege
		# We can use ports 1024-65535 in config file
		# if no listen is defined, then TCP can not connect
		listen			127.0.0.1:4242;
		# in curl, protect if no server_name match the host header in the request
		# If no server_name is defined in a server block then nginx uses the empty name as the server name.
		server_name		webserv.com www.webserv.com www.webserv.fr;

		#if no root, defined a default folder directly in the code
		root			/www/;

		index			index.html; # default index files

		# if no error_page, defined default page directly in the code
		error_page		403 404 /40x.html;
		error_page		500 502 503 504 /50x.html;

		# PREFIX MATCH (default behaviour)
		location / {
			autoindex			on;
			allowed_methods		GET POST DELETE;
		}

		location /src/ {
			autoindex			off;
			allowed_methods		GET;
			return				403 /403.html;
		}

		location = /old_page {
            return 301 /new_page;
            # Client receives:
            # HTTP/1.1 301 Moved Permanently
            # Location: /new_page
        }

		location /public/ {
			index	public_index.html;
		}

		location /upload {
			allowed_methods				POST DELETE;
			upload_authorized			ON;
			root						/root/;
			upload_storage_location		/upload/;
		}

		# 2 locations images to test that rule of longest prefix wins
		location /images/ {
			autoindex on;
		}

		location /images/icons/ {
			autoindex off;
		}
	}

	server {
		listen			127.0.0.1:4242 default_server;
		server_name		banana;
		# NGINX builds the filesystem path like this: root + URI only when a request is received
		# if file does not exist => 404 Not Found
		# if directory does not exist => 404 Not Found
		# if no permission to Access Directory => 403 Forbidden
		root			/www2/;

		# PREFIX MATCH (default behaviour)
		location / {
			index	index.html;
			# return 200 "Prefix match\n"
		}

		location = /old_page {
            return 301 /new_page;
            # Client receives:
            # HTTP/1.1 301 Moved Permanently
            # Location: /new_page
        }

	}

	server {
		listen			127.0.0.1:8080;
		server_name		banana;
		root			/www3/;
		location / {
			# no index directive => 403 or 404 (depends if autoindex enabled)
		}

		location /public/ {
			index	index.html;
			autoindex		on;
		}
	}
}