
	# By default, limit is 1M
	# Upload < 1MB → OK
	# Upload > 1MB → 413 Request Entity Too Large

	server{


		# Ports from 0 to 1023 requires root privilege
		# We can use ports 1024-65535 in config file
		# if no listen is defined, then TCP can not connect
		listen			8080 default_server;

		client_max_body_size 100m;
		# (O = Octet (default unit), K = kilo-octet, M = mega-octet, G = giga-octet)
		# in curl, protect if no server_name match the host header in the request
		# If no server_name is defined in a server block then nginx uses the empty name as the server name.
		server_name		webserv.com www.webserv.com www.webserv.fr;


		#if no root, defined a default folder directly in the code
		root			./html;

		index			default.html;
		# default index files

		# if no error_page, defined default page directly in the code
		error_page		403  403.html;
		error_page		505 /505.html;

		# PREFIX MATCH (default behaviour)
		location / {
			autoindex			on;
			allowed_methods		GET;
		}

		location /src/ {
			return 403 Forbidden;
		}

        location /includes/ {
            return 403 Forbidden;
        }

		location  /old_page {
            return 301 /images/;
            # Client receives:
            # HTTP/1.1 301 Moved Permanently
            # Location: /new_page
		}

		location /public/ {
			index	public_index.html;
            autoindex on;
			allowed_methods		GET;
		}

		location /upload {
            root    ./uploads;
			allowed_methods POST DELETE;
            upload_allowed  on;
            upload_location ./uploads;
		}

        location /cgi {
            root    cgi;
            cgi .py ./cgi/script.py;
            cgi .php ./cgi/script.php;
        }

		# 2 locations images to test that rule of longest prefix wins
		location /images/ {
            root ./images/;
            index http.jpeg;
			autoindex on;
            allowed_methods GET;
		}

		location /images/icons/ {
            root ./images/;
			autoindex off;
            allowed_methods GET;
		}
	}

	server {
		listen			4343 default_server;
		server_name		banana;
		# NGINX builds the filesystem path like this: root + URI only when a request is received
		# if file does not exist => 404 Not Found
		# if directory does not exist => 404 Not Found
		# if no permission to Access Directory => 403 Forbidden
		root			./html;
        autoindex on;
		# PREFIX MATCH (default behaviour)
		location / {
			index	default.html;
			# return 200 "Prefix match\n"
		}

		location  /old_page {
            return 301 /;
            # Client receives:
            # HTTP/1.1 301 Moved Permanently
            # Location: /new_page
        }
	}

	server {
		listen			8080;
		server_name		banana;
		root			./html;
		location / {
			# no index directive => 403 or 404 (depends if autoindex enabled)
		}

		location /public/ {
			index	index.html;
			autoindex		on;
            error_page  404 404.html;
            client_max_body_size 50m;
		}
        return 200 welcome_to_webserv;
	}
