
# server 1

## Server
    => std::vector<ServerConfig> servers_list;
server {
	listen			localhost:8080
        => std::string  listen; ==> to keep?
        => std::string  interface;
        => int          port;
	server_name		SERVER_NAME0 SERVER_NAME1
        => std::vector<std::string> server_name;
	root			ROOT0
        => std::string  root;
	index			INDEX0 INDEX1 INDEX2
        => std::vector<std::string> index;
	client_size		100 (equivalent to client_max_body_size)
        => int      client_max_body_size;
	methods			GET POST DELETE
        => std::vector<std::string> methods;
	error_page		300 ERROR_PAGE0
        => std::map<int, std::string> error_page; 
        => reject when several status_code is used on this line for example "error_page 300 301 /30x.html"
        => if directive not specify, use the default one
        => have a pre-filled map of error status with default page and update the string part if directive is found in the config file
	error_page		400 ERROR_PAGE1
	autoindex		on
        => bool autoindex;


## Location
    => std::vector<LocationConfig> location_list;

	location /DIRECTORY1/ {
        => std::string directory_path;
		root			ROOT1
            => std::string  root;
		index			INDEX
            => std::vector<std::string> index;
		client_size		2000
            => int      client_max_body_size;
		error_page		400 ERROR_PAGE2
            => std::map<int, std::string> error_page; 
		methods			GET
            => std::vector<std::string> methods;
		autoindex		off
            => bool autoindex;

	return REDIR_URL
        => std::map<int, std::string> return_page;
	}
	
	location *.php {
		cgi_pass	CGI
	}

	return REDIR_URL
        => std::map<int, std::string> return_page;
}

# server 2

server {
	listen			127.0.0.2:65465	# commentary
	server_name		SERVER_NAME
	root			ROOT2
	client_size		100
	methods			DELETE		  GET

	location /DIRECTORY1 {
		root			ROOT3/
		index			INDEX
		client_size		2000
		error_page		404 ERROR_PAGE3
		methods			GET
	}

	location /DIRECTORY2 {
		root			ROOT4
		index			INDEX5 INDEX6 INDEX7
		client_size		0
		methods			POST DELETE
		autoindex		on
	}

	location /DIRECTORY2/DIRECTORY3 {
		root			ROOT5
		index			INDEX8 INDEX9 INDEX10
		client_size		0
		methods			POST DELETE
		autoindex		on
	}

	location /TOREDIR {
		return REDIR_URL
	}
}